### ISSUE TITLE
Awful Flux Fill results. (blurry, grainy results)

### ISSUE THREAD

**Issue by JackDainzh** [comfyanonymous/ComfyUI#5746] opened 2024-11-23 15:28 UTC
### Expected Behavior
![tmptkjjhagi](https://github.com/user-attachments/assets/6da62741-36a1-4fd6-b523-4cbeb9c9bb86)

A proper image being generated without the said artifact (blurry, grainy). Like on the image above when generating on Replicate Space.

### Actual Behavior

Generates images with awful, mushy quality.
![ComfyUI_00086_](https://github.com/user-attachments/assets/8db88b59-0b45-4a4e-b185-34a4cb446010)
![ComfyUI_00088_](https://github.com/user-attachments/assets/c730d4f5-d4e7-495c-9695-c79e086603aa)

### Steps to Reproduce

Use a standard (recommended) workflow for flux fill. You can load either a standard 22 gb dev model, or use a GGUF one, the results are nearly the same. 

### Debug Logs

```powershell
no errors during and after generation.
```

### Other

Have encountered another person on CivitAI using an community made FP8 version of this model, who describes that the results are exactly the same as I am encountering.

**Comment by JackDainzh** [comment] 2024-11-23 15:46
After further inspection and testing with different inpaint methods, I can confirm that the issue lies within the InpaintModelConditioning node.

**Comment by yincangshiwei** [comment] 2024-11-24 07:05
It seems that not all GPUs are compatible, and there may be issues under certain seeds, only a few specific seeds are normal.
https://github.com/comfyanonymous/ComfyUI/issues/5715

**Comment by yincangshiwei** [comment] 2024-11-24 07:11
It should be related to this:
https://github.com/black-forest-labs/flux/pull/195

**Comment by JackDainzh** [comment] 2024-11-24 07:41
> It should be related to this: [black-forest-labs/flux#195](https://github.com/black-forest-labs/flux/pull/195)

Strange, I have RTX 4070 gpu, should work fine I think?

**Comment by Mozer** [comment] 2024-11-24 09:11
I have 2080ti-22GB and flux fill outpaint works bad (grainy) with high resolutions of the final image (more than 700x700). With lower res (632x696) it looks almost OK but still not perfect. With my 3060-12GB it works perfect. I tried fp16, fp8 and gguf_q4_0 checkpoints. Clip is fp8. Inpaint also suffers when high res.
Python version: 3.11.9
pytorch version: 2.5.1+cu121
comfyUI v0.3.4
![_ComfyUI_01592_ - ComfyUI - Google Chrome 24 11 2024 11_46_50](https://github.com/user-attachments/assets/7ca68e11-024a-4627-a88e-5acdf7586b2a)
![_ComfyUI_01592_ - ComfyUI - Google Chrome 24 11 2024 11_51_35](https://github.com/user-attachments/assets/5e2d9b46-f235-4e57-b5f8-3d8ba9d6e0a0)

**Comment by yincangshiwei** [comment] 2024-11-25 03:08
> I have 2080ti-22GB and flux fill outpaint works bad (grainy) with high resolutions of the final image (more than 700x700). With lower res (632x696) it looks almost OK but still not perfect. With my 3060-12GB it works perfect. I tried fp16, fp8 and gguf_q4_0 checkpoints. Clip is fp8. Inpaint also suffers when high res. Python version: 3.11.9 pytorch version: 2.5.1+cu121 comfyUI v0.3.4 ![ComfyUI_01592 - ComfyUI - Google Chrome 24 11 2024 11_46_50](https://private-user-images.githubusercontent.com/1599013/389260086-7ca68e11-024a-4627-a88e-5acdf7586b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDQzNTEsIm5iZiI6MTczMjUwNDA1MSwicGF0aCI6Ii8xNTk5MDEzLzM4OTI2MDA4Ni03Y2E2OGUxMS0wMjRhLTQ2MjctYTg4ZS01YWNkZjc1ODZiMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMDMwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTY1YmM2MzdmOTUwMGI5MjFkMDc5Y2Y5Zjg3N2RjMmY3M2QwNzYyZTg1NDEwN2RhZTM0ZTYzNDBjMmQxMGI0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2g7Iq4WMII7bYL5--3CXtsOGjSOnHNCifff-dWD7wFI) ![ComfyUI_01592 - ComfyUI - Google Chrome 24 11 2024 11_51_35](https://private-user-images.githubusercontent.com/1599013/389260091-5e2d9b46-f235-4e57-b5f8-3d8ba9d6e0a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDQzNTEsIm5iZiI6MTczMjUwNDA1MSwicGF0aCI6Ii8xNTk5MDEzLzM4OTI2MDA5MS01ZTJkOWI0Ni1mMjM1LTRlNTctYjVmOC0zZDhiYTlkNmUwYTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMDMwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk2YTcxZjM0NGJhYzhjNDJmNzZkZTZiOTJhN2I1MjZkMWQ3NWFmODY4ZWNkYjZkMzE1NzZhYTE0ZjNkYzU5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Lv1nHrj1N-aadX7mkwpH1jkT9Siur6h78lUMdqGf7DM)

I replaced the gguf with FP16 and it solved the problem. It doesn't happen again.

**Comment by taiyouZhang** [comment] 2024-11-25 08:07
me too, always wierd blurry

**Comment by catbaba777** [comment] 2024-11-25 08:51
I tried many times, depending on the resolution and expanding the area of ​​the image. Same goes for partial repaints. Noise appears when large areas are redrawn. Simple compositions and lower raw images are easier to achieve good results at 768 or 512 resolution. Additionally, it relies on random seeds. In short, very uncontrollable. .

**Comment by Mozer** [comment] 2024-11-25 13:39
I have successfully used Flux fill 1024x1024 20 steps on my 2080ti-22GB using this diffusers-bnb-nf4 code https://huggingface.co/sayakpaul/FLUX.1-Fill-dev-nf4
No noise on the sides that i have with comfy. But nf4 quality in the center is degraded a bit, compared to fp8 version that i have on my 3060. Inpaint and outpaint works. Inpaint looks better. uses 16 GB of vram. Original flux dev in diffusers version is needed to run this code.

python 3.11.10, cuda 11.8, torch: 2.5.1+cu118
![output_FLUX_1-Fill-dev-nf4_4bit](https://github.com/user-attachments/assets/d19d140c-27e1-4c10-987b-11914c8f8c81)
![output_FLUX_1-Fill-dev-nf4_4bit_11](https://github.com/user-attachments/assets/e3c817aa-8559-4d79-b69a-c5456362b2f2)

**Comment by willhsmit** [comment] 2024-11-26 02:03
Buried in a Swarmui commit
https://github.com/mcmonkeyprojects/SwarmUI/commit/d83fe849befad0df459456a4337a2698b85ed0ac

is the comment:
- Boosting the `Flux Guidance Scale` way up to eg `30` may improve quality

I can confirm that making this change is a substantial improvement for me on a few test generations.

**Comment by catbaba777** [comment] 2024-11-26 02:23
> I have successfully used Flux fill 1024x1024 20 steps on my 2080ti-22GB using this diffusers-bnb-nf4 code https://huggingface.co/sayakpaul/FLUX.1-Fill-dev-nf4 No noise on the sides that i have with comfy. But nf4 quality in the center is degraded a bit, compared to fp8 version that i have on my 3060. Inpaint and outpaint works. Inpaint looks better. uses 16 GB of vram. Original flux dev in diffusers version is needed to run this code.
> 
> python 3.11.10, cuda 11.8, torch: 2.5.1+cu118 ![output_FLUX_1-Fill-dev-nf4_4bit](https://private-user-images.githubusercontent.com/1599013/389548923-d19d140c-27e1-4c10-987b-11914c8f8c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODgwODcsIm5iZiI6MTczMjU4Nzc4NywicGF0aCI6Ii8xNTk5MDEzLzM4OTU0ODkyMy1kMTlkMTQwYy0yN2UxLTRjMTAtOTg3Yi0xMTkxNGM4ZjhjODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMDIyMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI3YmJiYjVjYjhmYzdjNWRlOTJhNTM2MzE5NDlhMjMwNjFjZTg3ZjMwNTM5MGE2NWYxODU4N2MzOWI5ZDNlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VFwDOi-RsUhP1EoxwV1-N3qFVX_4pvMKebU9S844r9I) ![output_FLUX_1-Fill-dev-nf4_4bit_11](https://private-user-images.githubusercontent.com/1599013/389549019-e3c817aa-8559-4d79-b69a-c5456362b2f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODgwODcsIm5iZiI6MTczMjU4Nzc4NywicGF0aCI6Ii8xNTk5MDEzLzM4OTU0OTAxOS1lM2M4MTdhYS04NTU5LTRkNzktYjY5YS1jNTQ1NjM2MmIyZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMDIyMzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWMwN2RhMWQ4OTU3Y2I5YzRjNjYyNzQ2NTNjNzkzOGFjYmY1MjgwOGNmNzY0ZDU4OWUxNjdhZGU0ZDdmODQ2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XGkir1YO5iWqnWT8GOX8MdYnmUlxGsoP68LGlfxxGaE)

No synthesized model found  ……

**Comment by JackDainzh** [comment] 2024-11-26 03:12
All these generations that are shown in my examples were made with Guidance of 30.

**Comment by willhsmit** [comment] 2024-11-26 03:27
Are you inpainting or outpainting? I ask because normally I expect a flux fill output to contain a mix of content leftover from the original image and generated content, and yours look uniformly mushy everywhere.

**Comment by JackDainzh** [comment] 2024-11-26 05:23
That was inpainting woth the whole image masked, to show the issue more clearly. As for generating with small patches, it's the same, new generated objects are mushy too

**Comment by comfyanonymous** [comment] 2024-11-26 06:36
Should be fixed now. The flux inpaint model does not work in fp16 unlike the other flux models. The fix is to make it inference in fp32 on cards that do not support bf16 which is slow but will make it work.

**Comment by Mozer** [comment] 2024-11-26 06:56
Thx, I can confirm it is working for my 2080ti now, though slower.

**Closed** 2024-11-26 07:09 UTC
Labels: Potential Bug

**Comment by GXcells** [comment] 2024-12-08 20:47
> Should be fixed now. The flux inpaint model does not work in fp16 unlike the other flux models. The fix is to make it inference in fp32 on cards that do not support bf16 which is slow but will make it work.

How do you infer in fp32? In "weight dtype" I only have default or the fp8 versions

**Comment by jeremyxliminal** [comment] 2025-02-05 18:44
how do we make it inference in fp32?

**Comment by Mozer** [comment] 2025-02-07 06:25
> > Thx, I can confirm it is working for my 2080ti now, though slower.
> 
> Can you explain how you did this or provide a tutorial link? Спасибо)

Just update your comfyui using update_comfyui.bat

**Comment by daignat** [comment] 2025-02-07 14:53
> Just update your comfyui using update_comfyui.bat

Already done, but the problem described in the topic is not solved

@comfyanonymous @Mozer 

![Image](https://github.com/user-attachments/assets/783017ba-de93-40fe-8999-68b4a8800908)
