### ISSUE TITLE
Text on the canvas looks low resolution/fuzzy

### ISSUE THREAD

**Issue by subashc2023** [comfyanonymous/ComfyUI#100] opened 2023-03-16 06:26 UTC
I thought it might be some kind of scaling issue because I have a 2560x1440 monitor, but resizing the window, or running it in a different monitor produces the same issue. It also causes some kerning issues

The little window with the Queue is sufficiently high resolution, and even the text inside the prompt box is high resolution, it is just the UI elements in the Canvas, as well as the FPS, and TINV counter at the bottom left that are fuzzy.

![image](https://user-images.githubusercontent.com/120974338/225532867-c1d7cbde-5b75-4b47-b383-21679f1345b0.png)

**Comment by subashc2023** [comment] 2023-03-16 06:27
seems to be related to the zooming functionality?

**Comment by MalOMaw** [comment] 2023-03-17 08:45
I have a 2560x1440 monitor too, it does look like this

**Comment by Zentropivity** [comment] 2023-03-17 09:22
Can you check if #109 fixes it?
It has added viewport meta tags in html header which may be needed.

**Comment by subashc2023** [comment] 2023-03-17 09:40
I don't think it has fixed the issue. Text still low res.

**Comment by Zentropivity** [comment] 2023-03-17 10:14
duplicate of #36

**Comment by robinjhuang** [comment] 2024-07-03 21:46
Marked as fixed.

**Closed by robinjhuang** 2024-07-03 21:46 UTC
