### ISSUE TITLE
Is there a way to convert api.json back to. json format？

### ISSUE THREAD

**Issue by GeLi1989** [comfyanonymous/ComfyUI#1559] opened 2023-09-19 14:43 UTC
If I get the api.json file，Is there a way to convert api.json back to. json format？
How to do this？

thanks！

**Comment by wcurti** [comment] 2023-09-19 15:47
Not at present, no.

**Comment by mcmonkey4eva** [comment] 2023-09-23 07:00
Duplicate of #1498

**Closed by mcmonkey4eva** 2023-09-23 07:00 UTC
