### ISSUE TITLE
unable to use Save Image node or Preview Image node

### ISSUE THREAD

**Issue by CCJetWing** [comfyanonymous/ComfyUI#4006] opened 2024-07-12 07:25 UTC
### Expected Behavior

I could save and preview the images a few days ago.

### Actual Behavior

From yesterday onward after updated the nodes, it gives the following message:

Prompt outputs failed validation: Exception when validating node: name 'full_type_name' is not defined
SaveImage:
- Exception when validating node: name 'full_type_name' is not defined

### Steps to Reproduce

It works when I use Empty Latent Image node but error comes out when I use VAE Encode (for Inpainting) node and Set Latent Noise Mask node pairs. 

### Debug Logs

```powershell
got prompt
Failed to validate prompt for output 9:
* (prompt):
  - Exception when validating node: name 'full_type_name' is not defined
* SaveImage 9:
  - Exception when validating node: name 'full_type_name' is not defined
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': "Exception when validating node: name 'full_type_name' is not defined", 'extra_info': {}}
```

**Comment by huchenlei** [comment] 2024-07-12 13:22
Have you tried disable all custom nodes? You can do that by passing `--disable-all-custom-nodes` flag

**Comment by ltdrdata** [comment] 2024-07-12 23:40
The input name `full_type_name` is strange. Can you share your workflow?

**Comment by fyepi** [comment] 2024-07-16 03:38
I have encountered the same problem. The images have been generated and could be found under output folder but they don't show up in preview node.

There is no error on console at all. The workflow is a most minimal one. 

![image](https://github.com/user-attachments/assets/ac226f88-2637-4268-b7bc-0a0c1cb3acdb)

**Comment by fyepi** [comment] 2024-07-16 03:59
It seems to be a browser compatibility issue. The problem happens on Edge on Ubuntu 22.04. When using chrome no such problems.

**Comment by kevinmarkwardt** [comment] 2024-08-16 19:59
I do not think it's browser related, I am getting this error after updating to the latest update of ComfyUI

**Comment by kevinmarkwardt** [comment] 2024-08-16 20:17
Did another test with the default workflow and add a couple ip adapter nodes and got the error.
![Screenshot 2024-08-16 161722](https://github.com/user-attachments/assets/1a117fe0-55d8-4896-9842-39054574d1ec)

**Comment by kevinmarkwardt** [comment] 2024-08-16 21:37
Seems to be some sort of custom node that caused it.  Started from a fresh comfy_ui and installed most of the custom nodes back and the issue is gone.  I am good with closing this on my part.

**Comment by UfiChyon** [comment] 2024-08-26 07:08
Hi.
I was having the same problem, and after exploring the custom nodes one by one, it seems that the node {ComfyUI_ezXY} was doing something wrong, so I deleted it and the error disappeared.

**Comment by CCJetWing** [comment] 2024-08-26 10:13
> Hi. I was having the same problem, and after exploring the custom nodes one by one, it seems that the node {ComfyUI_ezXY} was doing something wrong, so I deleted it and the error disappeared.

I think I am having the same problem, after disabled the node, it remains normal, thank you.

**Closed** 2024-08-26 10:22 UTC
Labels: Frontend, Potential Bug, Browser Related

**Comment by bitsentinel-cell** [comment] 2024-09-02 10:00
> Hi. I was having the same problem, and after exploring the custom nodes one by one, it seems that the node {ComfyUI_ezXY} was doing something wrong, so I deleted it and the error disappeared.

how did you figure that out?

**Comment by UfiChyon** [comment] 2024-09-09 09:25
I found the root of the error, the custom node, by removing all custom node from the custom node folder one by one and inserting the custom node while launching ComfyUI each time.

**Comment by JonnyJV** [comment] 2024-09-27 04:37
> I found the root of the error, the custom node, by removing all custom node from the custom node folder one by one and inserting the custom node while launching ComfyUI each time.

Only problem is.. some of us have about 10,000 custom nodes installed.

**Comment by ltdrdata** [comment] 2024-09-27 06:34
> > I found the root of the error, the custom node, by removing all custom node from the custom node folder one by one and inserting the custom node while launching ComfyUI each time.
> 
> Only problem is.. some of us have about 10,000 custom nodes installed.

The method developers use to find such issues is called binary search or halving.
Using this method, even with 10,000 custom nodese, you can find the cause with just a few tests.

First, remove half of the installed custom nodes and test. If the problem persists, remove half of the remaining nodes and continue this process.
If the problem doesn't reproduce, swap the remaining nodes with the ones you removed, then remove half of these and test again.

**Comment by BlairBrooksBB** [comment] 2025-02-20 19:40
> Hi. I was having the same problem, and after exploring the custom nodes one by one, it seems that the node {ComfyUI_ezXY} was doing something wrong, so I deleted it and the error disappeared.

This did the trick getting rid of that folder or node, fixed that situation for me.
