### ISSUE TITLE
Imported API json : Titles missing

### ISSUE THREAD

**Issue by seghier** [comfyanonymous/ComfyUI#3253] opened 2024-04-12 21:44 UTC
Hello
I save a workflow as API format , and i already change the tiltles of some nodes but when i load the api json, all titles gone from the workflow, and they still exist in the json file.

![image](https://github.com/comfyanonymous/ComfyUI/assets/6026588/04ba6f34-556a-4bce-bcfd-0fbd8172fb84)

![image](https://github.com/comfyanonymous/ComfyUI/assets/6026588/258a1552-7414-4248-af38-1b9a294f372a)

**Comment by shesung** [comment] 2024-07-12 08:13
still not fixed yet

**Comment by robinjhuang** [comment] 2024-07-17 23:34
Duplicate of this: https://github.com/comfyanonymous/ComfyUI/issues/3307
Please don't re-submit the same issue.

**Closed by robinjhuang** 2024-07-17 23:34 UTC
