### ISSUE TITLE
random image previews in unrelated nodes

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#4351] opened 2024-08-14 10:05 UTC
### Expected Behavior

See preview in appropriate node.

### Actual Behavior

![image](https://github.com/user-attachments/assets/5e99e869-d774-40c6-b7a7-b1c1480a883b)

Stuff like this, it's a preview in the checkpoint loader, but I have seen this happen in basically a ton of different nodes, where the image really is not supposed to be. It's just the latest where I thought this cannot be right.

### Steps to Reproduce

run comfy

### Debug Logs

```powershell
None
```

**Comment by ltdrdata** [comment] 2024-08-14 13:47
@huchenlei 
This issue has been occurring for a long time. It seems to arise when loading a new workflow on top of an existing preview generated from a previous workflow execution. The problem appears to be caused by an attempt to maintain the `img` when there are nodes with IDs identical to those in the existing workflow.

I hope this issue will be resolved in the new frontend.

**Comment by mcmonkey4eva** [comment] 2024-08-17 05:36
frontend issues go @ https://github.com/Comfy-Org/ComfyUI_frontend/

**Closed by mcmonkey4eva** 2024-08-17 05:36 UTC
Labels: Bug, Frontend, Potential Bug
