### ISSUE TITLE
Issue with ComfyUI on AMD

### ISSUE THREAD

**Issue by GameBack02** [comfyanonymous/ComfyUI#1576] opened 2023-09-22 21:47 UTC
I have a RX 580 with 4GB of VRAM and I'm on Windows 11, I am used to generating images in A1111, it works fine but I wanted to see if ComfyUI would make it better me, since I heard it is less resource hungry than A1111.
Here are some pictures of what it looks like when I try to generate with different launch arguments, I'm very not smart with this stuff, I just followed some guides and got some help from people but this is the most we could figure out, I got told to open an issue since everything looked to be in place...
My system specs are:
Prime B450M gaming/br motherboard
Ryzen 5 3600x
16GB of RAM
Asus RX 580 4GB
If any additional data is needed I'll try my best to provide them!

![Untitled](https://github.com/comfyanonymous/ComfyUI/assets/143299467/1b1e0677-de1c-4203-936a-83d60b7cbe0d)
![Untitled2](https://github.com/comfyanonymous/ComfyUI/assets/143299467/107f20da-98f3-4003-9f36-49d9d83175c0)
![Untitled3](https://github.com/comfyanonymous/ComfyUI/assets/143299467/e0c53f60-028d-47a0-8a4c-3d49cd5bcc35)
![image (1)](https://github.com/comfyanonymous/ComfyUI/assets/143299467/cbb08338-a524-4e9a-bb0f-180feb32424e)

**Comment by rabidcopy** [comment] 2023-09-23 00:30
If you were using Auto1111 previously and not a fork that supports directml AFAIK you were using CPU for inference since you're on Windows. It either looks like your python environment doesn't have the directml version of torch installed and/or 4GB is just not enough to use directml with ComfyUI. Possibly a dupe of https://github.com/comfyanonymous/ComfyUI/issues/939.

**Closed** 2023-09-23 07:17 UTC
