### ISSUE TITLE
3 times slower for first generation of a loaded workflow (the model is already loaded so no related)

### ISSUE THREAD

**Issue by menahem121** [comfyanonymous/ComfyUI#4041] opened 2024-07-17 09:14 UTC
### Expected Behavior

Hi i just installed the new cuda 12.5 driver and the nightly version of torch etc.. but now when loading a new workflow i get a warning message

it is working but the first generation with a new loaded workflow take 3X more times 

### Actual Behavior

i dont know if its related but its for 3 times slower for first generation on workflow with the exact same model already loaded
the warning log:
```
/home/ubuntu/.local/lib/python3.10/site-packages/torchsde/_brownian/brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=0.44691839814186096 and t1=0.446918.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")```
  ```
  

### Steps to Reproduce

Cuda 12.5 update 1
with pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124

### Debug Logs

```powershell
/home/ubuntu/.local/lib/python3.10/site-packages/torchsde/_brownian/brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=0.44691839814186096 and t1=0.446918.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
```

EDIT:

i tried on my other with CUDA 12.3 wher i used to work and i just realize its doing the same, instead of 3sec per generated image it takes 8 seconds for the first image when im loading another workflow

this is a real issue for me cause i want to use ComfyUI as server and send request that will use multiple workflows ive made

**Comment by mcmonkey4eva** [comment] 2024-07-18 20:44
closing as duplicate of https://github.com/comfyanonymous/ComfyUI/issues/4053

**Closed by mcmonkey4eva** 2024-07-18 20:44 UTC
Labels: Potential Bug
