### ISSUE TITLE
ZLUDA support

### ISSUE THREAD

**Issue by zcq06** [comfyanonymous/ComfyUI#2819] opened 2024-02-18 04:53 UTC
SD.NET has preliminarily supported the use of ZLUDA on amd gpu, and the efficiency is very high, which is three times that of rocm. Can the method of adapting SD.NET be used for preliminary adaptation now?
https://github.com/vladmandic/automatic/wiki/ZLUDA
https://github.com/vladmandic/automatic/commit/cc4438651f69973e055b63071bf1d0e3cc558eea
https://github.com/vosen/ZLUDA

**Comment by Th3Rom3** [comment] 2024-02-18 07:31
Duplicate of #2810

**Comment by zcq06** [comment] 2024-02-18 11:40
Duplicate of https://github.com/comfyanonymous/ComfyUI/issues/2810

**Closed** 2024-02-18 11:43 UTC
