### ISSUE TITLE
fix custom nodes load

### ISSUE THREAD

**Issue by ahmederaqi95** [comfyanonymous/ComfyUI#5456] opened 2024-11-01 13:43 UTC
### Your question

hello
i have a problem loading some custom nodes in many workflows.
it shows try to fix. but after restarting nothing happen.
some times there are some missing nodes, but when i try to install using comfy manager it shows empty box.
i tried to change from dev to default and change security to weak. sometime it work sometimes not working.

### Logs

```powershell
custom_nodes, manager, load
```

**Comment by ltdrdata** [comment] 2024-11-01 21:03
Firstly, this issue is related to ComfyUI-Manager, not ComfyUI, so it should be addressed in the ComfyUI-Manager repository.

The reason 'try' is prefixed to 'try fix' is due to this context.

Generally, if an import error occurs, it’s highly likely caused by issues in installing pip dependencies. The default installation process uses a lighter pip installation to avoid issues, but 'try fix' attempts to resolve the issue by forcibly reinstalling pip.

However, not all problems can be solved with this method. Although we're considering better solutions in the future, there are currently limitations with this function.

**Closed by ltdrdata** 2024-11-01 21:03 UTC
Labels: User Support
