### ISSUE TITLE
The webui  can be used for a period of time and then no response

### ISSUE THREAD

**Issue by LeeKIngKIng** [comfyanonymous/ComfyUI#3980] opened 2024-07-09 02:21 UTC
### Your question

The webUI  can be used for a period of time and then no response.
When I click the button 'Queue Prompt', the backend can print out message normally.
Finally I find out that there's something wrong with the function 'publish_loop' in the Class 'PromptServer'.
'self.messages.put_nowait' can normally add item into the queue, but 'await self.messages.get()' is stuck and the msg can't be sent out by socket any more.
How can I fix this Problem?

**Comment by huchenlei** [comment] 2024-07-09 14:03
Can you write down detailed reproduction steps? e.g. 1. Click ... 2. Click .. 3. Observe ...

**Comment by LeeKIngKIng** [comment] 2024-07-10 01:20
> Can you write down detailed reproduction steps? e.g. 1. Click ... 2. Click .. 3. Observe ...

There's no step. The webUI can run normally for a period of time. Maybe one hour, maybe two...But finally it will be no response.
I find out that the code  'await self.messages.get()' is stuck, but I don't know why and how it happens?

**Comment by huchenlei** [comment] 2024-07-10 01:47
Hmmm, seems to be a hard to repro flaky issue. How did you managed to get down to `await self.messages.get()`?

**Comment by LeeKIngKIng** [comment] 2024-07-10 02:23
> Hmmm, seems to be a hard to repro flaky issue. How did you managed to get down to `await self.messages.get()`?

when there’s no response on the webui, the http request works and the terminal prints out the logging info，so I realize that the problem is on the socket. Just step by step.
post_prompt > prompt_queue.put > queue_updated > send_sync
and finally  'await self.messages.get' in publish_loop is stuck

**Comment by LeeKIngKIng** [comment] 2024-07-11 01:58
Fortunately，I finally find out that it's the custom nodes named [Crystools](https://github.com/crystian/ComfyUI-Crystools) which causes this problem. All I have to do is to disable it. Maybe it sends too many socket messages? I don't know the deep reason.

**Comment by huchenlei** [comment] 2024-07-11 02:45
Hmmm. Maybe you can file an issue in the custom node repo instead. Closing this for now.

**Closed by huchenlei** 2024-07-11 02:45 UTC
Labels: Bug, User Support, Flaky

**Comment by ltdrdata** [comment] 2024-07-11 12:20
> Fortunately，I finally find out that it's the custom nodes named [Crystools](https://github.com/crystian/ComfyUI-Crystools) which causes this problem. All I have to do is to disable it. Maybe it sends too many socket messages? I don't know the deep reason.

@crystian Maybe the resource monitor is causing this error.
