### ISSUE TITLE
Nodes aren't appearing on top of others when clicked on

### ISSUE THREAD

**Issue by DB1052** [comfyanonymous/ComfyUI#4406] opened 2024-08-16 13:05 UTC
### Your question

I tend to hide minor nodes that don't require input underneath other nodes to declutter workflows. For example, I might hide a batch image node underneath the ksampler node. However, with the latest update, clicking on nodes doesn't bring them to the top of the workflow. If you create a ksampler node followed by a batch image node, the batch image node will always sit on top.

**Comment by JorgeR81** [comment] 2024-08-16 13:33
It's due to the new Comfy UI frontend.
This issue is already open in the frontend repo.
https://github.com/Comfy-Org/ComfyUI_frontend/issues/438

**Comment by huchenlei** [comment] 2024-08-16 13:56
Duplicate of https://github.com/comfyanonymous/ComfyUI/issues/4383

**Closed by huchenlei** 2024-08-16 13:56 UTC
Labels: duplicate, User Support
